print("🔴🔵🟡🟢 Reglas del juego UNO 🃏")
print("1. Cada jugador comienza con 7 cartas.")
print("2. Los jugadores deben colocar una carta que coincida en número, color o símbolo con la última carta jugada.")
print("3. Si un jugador no puede jugar, debe robar una carta del mazo.")
print("4. Las cartas especiales cambian el flujo del juego:")
print("   - Cambio de dirección: Invierte el orden de juego.")
print("   - Salta turno: El siguiente jugador pierde su turno.")
print("   - +2 y +4: Obliga al jugador siguiente a robar cartas.")
print("5. Para ganar, un jugador debe quedarse sin cartas y decir 'UNO' antes de que alguien lo detecte.")
print("6. Si un jugador olvida decir 'UNO', debe robar dos cartas.")
print("7. El juego continúa hasta que alguien alcance el puntaje objetivo o se termine el mazo.")